- name: Common tool setup on all the servers
  hosts: appsrvgrp
  become: yes
  tasks:
    - name: Install JDK on Ubuntu 14/15/16/18
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes
      when: ansible_distribution == 'Ubuntu' 

    - name: Install tomcat10 on Ubuntu 14/15/16/18
      apt:
        name: tomcat10
        state: present
        update_cache: yes
      when: ansible_distribution == 'Ubuntu' 

    - name: Start & Enable TOmcat 10
      service:
        name: tomcat10
        state: started
        enabled: yes

   
